### ISSUE TITLE
Using transports or destinations on edges

### ISSUE THREAD

**Issue by good-lly** [maou-shonen/hono-pino#48]
Did you manage to work any transport interface in edge like interfaces? Afaik pino is able to run only in single thread mode inside hono (and cloudflare)
Node/Bun is different story ....

**Comment by maou-shonen** [comment]
Hi! I haven’t actually used this in an edge environment.
A few days ago, I tried running it on Cloudflare Workers, and I didn’t encounter any errors (screenshot from #1 reply).

I’ve never heard that pino can only run in a single threaded mode!
If that’s true, then the issue would stem from limitations within pino itself.
While it’s possible to create a driver layer to address this, it seems beyond the scope of hono-pino.

If you could provide more specific errors or suggestions for issues running in an edge environment, that would help me solve the problem faster.
Otherwise, it may take a little while, as I’ve been quite busy lately and haven’t had much time for investigation.

Other ideas are also welcome.

**Comment by maou-shonen** [comment]
I found the cause of the error, and I'll fix it soon.

**Comment by maou-shonen** [comment]
I've confirmed that currently, pino transport doesn't seem to work on Cloudflare Workers,
but you can use the browser.write option as an alternative.

https://github.com/maou-shonen/hono-pino/releases/tag/v0.6.0 This version fixes a bug that caused errors on Cloudflare Workers
